### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by arthursoares** [envisioning/techdb#105]
I'll be adding some of the changes and fixes to the Menu here.

<img width="620" alt="envisioning_-_tech_db" src="https://cloud.githubusercontent.com/assets/533339/13472941/e5fd5b4a-e095-11e5-9cee-a036a3114565.png">

<img width="214" alt="envisioning_-_tech_db" src="https://cloud.githubusercontent.com/assets/533339/13473064/6a6bda14-e096-11e5-8634-6bc9b6041177.png">

- [ ] Change the menu default styling to this expanded view
- [ ] Add a search box on the menu.
- [ ] Remove the dropdown button and make the href directly to the dashboard

**Comment by lnmunhoz** [comment]
The collapsed menu should not have submenus either?

**Comment by arthursoares** [comment]
@lnmunhoz I should close this issue. Please see the thread on Slack. We'll follow up from there.

**Comment by lnmunhoz** [comment]
:+1:
