### ISSUE TITLE
login

### ISSUE THREAD

**Issue by arthursoares** [envisioning/techdb#14]
I think this one is pretty self-explainatory. But I'd like to scope some features for login options. Not necessarily for this release :)

- [ ] E-mail & password
- [ ] Google Account
- [ ] Facebook Account

**Comment by arthursoares** [comment]
@rafaelcorreiapoli 

----

Login functionalities for TechDB
## Specification
Login screen with some login options:
- Password
- Google +
- Facebook

User accounts features:
- The user should be invited by the Administrator through the admin panel. An email will be sent to the user with a link to activate and set his password
- The user can recover his password by email

![login](https://cloud.githubusercontent.com/assets/12840136/12218698/a61f7a2c-b70e-11e5-8cbe-ee2cbf98ce92.png)

**Comment by arthursoares** [comment]
:+1:

**Comment by rafaelcorreiapoli** [comment]
Hmm, we got a problem.
We invite new users via email, therefore only users allowed by admins can access the system. If we allow facebook/google+ login, then anyone could login in techDB

**Comment by michellzappa** [comment]
Rafael is 100% correct.
I think we can disregard all “Open” login providers for now.
Invite only!
