### ISSUE TITLE
mainDashboard

### ISSUE THREAD

**Issue by arthursoares** [envisioning/techdb#15]
This is the view that you get right after logging in.

## Features

- [ ] Recent updates: techs, projects, etc…
- [ ] Shortcuts to the main areas: Technologies, Projects, Attachments, Organizations, etc…
- [ ] Show recently updated technologies
- [ ] Show recently updated collections
- [ ] Statistics, much like a dashboard. Some ideas: **Users with most active projects**, **Most used techs**, etc…

**Comment by arthursoares** [comment]
by @rafaelcorreiapoli 

----

## Specification
The main dashboard is the first screen after user login. Shows relevant information about techDB entities and recent updates.

#### Component Dependencies
- dashboardStat #33 
- recentUpdates #34 
- **more[?]**

#### Complete Screen
![screen main dashboard](https://cloud.githubusercontent.com/assets/4376835/12218678/10600010-b70e-11e5-8eba-47823d24e201.png)

**Comment by rafaelcorreiapoli** [comment]
@arthursoares 
- Should we place any charts or rankings for this first version of mainDashboard?
- Should we have different boxes to show recentUpdates for each entity or one big list with all of them is fine ?

**Comment by michellzappa** [comment]
Keep it simple! Focus on MVP.

Charts and rankings can almost definitely be skipped for now (unless I'm
missing something).
