### ISSUE TITLE
userDashboard

### ISSUE THREAD

**Issue by arthursoares** [envisioning/techdb#24]
This is the main interface for displaying users list.

## Features

- [x] List of users with easy access to edit / create / delete
- [x] List with "Latest Access Time"
- [x] Easy to edit projects permissions to users.

## Reference

Dashboard v4 on INSPINIA should be a good reference.

<img width="1232" alt="screen shot 2016-01-07 at 4 12 57 pm" src="https://cloud.githubusercontent.com/assets/533339/12178616/930f382a-b559-11e5-8093-3ceacd412b17.png">

**Comment by rafaelcorreiapoli** [comment]
How does the "permissions on projects" system works?

**Comment by lnmunhoz** [comment]
More specific question: Permissions are for a specific project or an user that can edit a project can edit any project?

**Comment by michellzappa** [comment]
Permissions are per project.
It's basically a token saying the User is working on Projects.

**Comment by lnmunhoz** [comment]
:+1:

**Comment by lnmunhoz** [comment]
We are discussing about the **Easy to edit projects permissions to users.** on this screen. We are concerned about how to display

**Comment by lnmunhoz** [comment]
@michellzappa Is there one level of permission or multiple levels? Like one permission to view, one permission to delete, one permission to edit, etc... Or just one permission like Access to the project?

**Comment by michellzappa** [comment]
Just access!
Only Admins can delete/create projects.

**Comment by lnmunhoz** [comment]
Ok so #44 solves the problem :+1:

**Comment by michellzappa** [comment]
Perfect!

**Comment by arthursoares** [comment]
A screen to view and manage all users
## Specification

### Manage
A search box that will regex search all row's texts
Button group to toggle between *List view* and *Grid View*
A FAB (Floating action button) to add new entry

#### List View:
Datatable with these columns:
- Name
- Group (roles)
- Last Time Access
- Status (online or offline)
- Actions \*

\* Edit: opens a modal to quickly edit organization
\* Delete: opens a confirmation dialog to delete organization
\* Manage Group Permissions: Opens a modal to change user's role
\* Manage Project Permissions: Opens a modal to view/grant/revoke projects permissions for this particular user #44

The table can be sorted by any column, will have pagination and a dropdown to select how many rows will be shown per page
![list view](https://cloud.githubusercontent.com/assets/12840136/12218947/e9649b66-b716-11e5-95aa-4e4c63fe8f3f.png)

### Grid View
A grid of aboutCards #39  
![grid view](https://cloud.githubusercontent.com/assets/12840136/12218949/f0fa6d92-b716-11e5-9f30-bc1597c8493b.png)

**Features [?]**:
Pagination ?
Infinite Scroll ?
Sorting ?


### Complete screen
![complete screen](https://cloud.githubusercontent.com/assets/12840136/12218965/95baa3c4-b717-11e5-92f2-f0f25e8891cb.png)

**Comment by arthursoares** [comment]
@lnmunhoz you can check user permissions at #25

**Comment by rafaelcorreiapoli** [comment]
![user dashboard](https://cloud.githubusercontent.com/assets/12840136/13074488/f19c72a8-d48b-11e5-82d2-f4c1beee56c4.png)

**Comment by rafaelcorreiapoli** [comment]
Later, we can implement filters by Country and Affiliation
