### ISSUE TITLE
userEntry

### ISSUE THREAD

**Issue by arthursoares** [envisioning/techdb#25]
Expanded user view screen. It allows for consulting and editing the entry. 

Check #7 for fields and DB scheme.

### Roles

| ID | Actions | Admin  | Editor | Viewer
| :----| :------------ |:---------------:|:-----:|:-----:
|0| Add, Edit & Delete Users | X | | |
|1| Add, Edit & Delete Project | X | | |
|2| Add, Edit & Delete Organizations | X | X | |
|3| Add, Edit & Delete Technologies  | X | X | |
|4| Add, Edit & Delete Attachments  | X | X | | 
|5| per Project: Add, Edit & Delete collection  | X | X | |
|6| per Project: Add, Edit & Delete Attachment  | X | X | |
|7| per Project: Add, Edit & Delete Technology  | X | X | | 
|8| per Project: Browse technologies and collections  | X | X | X |
|9| per Project: Create a new Survey  | X | X | | 
|10| per Project: Create Godzilla Export  | X | X | |
|11| per Project: Create PDF Export  | X | X | |
|12| Search for technologies  | X | X | X |
|13| Fill Survey | X | X | X |

## Feature Requests

- [ ] Quickly edit contact info and permissions.

**Comment by arthursoares** [comment]
@rafaelcorreiapoli 

---


A screen to show everything about a specific User

## Specification
Composed by three main components:
### User card on the left panel
userCard #45 

### Recent Activities for this user
recentUpdates #34 

### Projects that this user is working
simpleList #36 
![complete screen v2](https://cloud.githubusercontent.com/assets/12840136/12219269/5570ef56-b723-11e5-8b72-6e055bcb40c2.png)

**Comment by lnmunhoz** [comment]
Should use #20 as a reference for this user card too? @arthursoares @michellzappa

**Comment by arthursoares** [comment]
@lnmunhoz yes!

**Comment by lnmunhoz** [comment]
For now we just need **0**, **1**, **2**, **3** and **4**.

**Comment by arthursoares** [comment]
@lnmunhoz can you explain how this would affect permissions for projects? why can't we implement this already?

**Comment by lnmunhoz** [comment]
Sorry I explained the wrong way @arthursoares . 

We can implement but there's no UI for using this per Project permission by now. For now we have just the basic stuff for projects (CRUD operation with **name** and **description**). 

I think its better to do when we create the real UI for that and focus in what's gonna be used now.

**Comment by rafaelcorreiapoli** [comment]
@arthursoares I have an important doubt
There are two interpretations of the sentence "per project"
1. Boolean: Or the user has full access on the project (limited by his role) or he has no access at all.
Example:
The User is an Editor, if he has Project A on his "projectsId" #7 , he can do 5,6,7,8,9,10,11
If he does not have Project A on his "projectsId", he can do nothing with that Project

2. Different set of permissions on each project
User A is an Editor, he can do 5,6,7 in Project A and 5,7,8 on Project B.
User B is an Editor, he can do 5,10,11 in Project A and 8 on Project B

These two scenarios configure a completely different db scheme. The one we designed fits the first scenario.
Which one is a requisite for TechDB?

**Comment by michellzappa** [comment]
In my non-technical opinion, Boolean access from user to project is
preferable. Keeping it simple, etc.

**Comment by arthursoares** [comment]
Agree with @michellzappa

**Comment by lnmunhoz** [comment]
Perfect!
