### ISSUE TITLE
attachmentDashboard

### ISSUE THREAD

**Issue by arthursoares** [envisioning/techdb#28]
Attachments view.

## Features

- [x] Activity log
- [x] Easy access to Attachments
- [ ] Sort by project, organization, user & tech.

## References

It would be nice if it followed a "card-like" design (Ref. Twitter / Facebook / Google).

**Comment by lnmunhoz** [comment]
### Specification

- For attachment management: searchAttachmentsContainer #50 
- For activity log: recentUpdates #34 

What you think @arthursoares ?

**Comment by lnmunhoz** [comment]
**Question**: Do you need any upload system as an alternative to attach files when it's not hosted anywhere on the web ?

**Comment by arthursoares** [comment]
@lnmunhoz
:+1: for both Specs.

**Upload system**: Nope, we don't have any currently. We'd love to have something hosted on S3.

**Comment by rafaelcorreiapoli** [comment]
Ok ! we will setup a S3 instance to host all files uploaded to TDB =)

**Comment by lnmunhoz** [comment]
:+1:

**Comment by rafaelcorreiapoli** [comment]
searchAttachmentsContainer was removed from the first Milestone. Anyway, we built a searchable attachments dashboard with full-text search funcionalities. I suppose that "Sort by project, organization, user & tech." must be on another milestone, right?
If so, should we close this issue?

**Comment by lnmunhoz** [comment]
@rafaelcorreiapoli Agreed. Waiting for @arthursoares now.

**Comment by michellzappa** [comment]
Agreed.

**Comment by arthursoares** [comment]
@rafaelcorreiapoli Yep, postpone it.
