### ISSUE TITLE
attachmentEntry

### ISSUE THREAD

**Issue by arthursoares** [envisioning/techdb#29]
This is more of an element than a screen. Similar to #11, this is the design unit for attachments, that might be used everywhere in the app.

Attachments can be associated to: Technologies, Organizations, Users & Projects

## Features

- [x] Image
- [x] Title
- [x] Description
- [x] URL / Link
- [x] # of projects
- [x] # of technologies
- [x] # of org
- [x] # of users

**Comment by lnmunhoz** [comment]
This attachmentCard #49 solves the problem?

**Comment by arthursoares** [comment]
Yes! @lnmunhoz

**Comment by arthursoares** [comment]
@lnmunhoz @rafaelcorreiapoli 

I think I need to explain a bit further Attachments and Images. So attachments are made of two kinds of objects: 

1. **URLs** - articles, blog posts, websites, etc…
2. **Files** – PDFs, JPGs, etc…

They should have some expected behaviors:

**URLs** if they are an HTML/Page, TDB should return the Meta to create the card. This will only reference.
**URLs** if they are images or files, TDB should make a copy and host the files somewhere (I suppose we'll have a S3?)
**Files** always uploaded to our servers.

Does this makes sense?
