### ISSUE TITLE
Visualization of lists

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#31]
What do you prefer for visualizating lists?
**Datatables:**
![technologies list](https://cloud.githubusercontent.com/assets/12840136/11760471/66db6b8c-a084-11e5-8a54-8b033bdc2421.png)
advantages:
- easy to develop
- sorting functions out of the box
- pagination
- more data on less space

**Cards:**
Grid of cards with a search input
advantages:
- better design

**Comment by arthursoares** [comment]
I really think we'll have to use both. With a toggle switch on the page.
