### ISSUE TITLE
elasticSearch

### ISSUE THREAD

**Issue by arthursoares** [envisioning/techdb#32]
Some examples:

- [x] Technology: Title, Description & Tags
- [x] Users: Name, Country
- [x] Attachments: Title
- [x] Project's title or description or ID
- [x] Project's collection by Name or description
- [x] Technology title synonyms
- [x] readiness handler: ie: **RD:>3** or **RD:3** or **RD:<3>2**
- [x] impact handler: ie: **IP:>3**
- [ ] Tag: ie: **tag:drone** or **tag:drone, delivery"
- [x] Project handle: ie: **ID:ev091**
- [x] Date of creation/update: ie: **before:10/10/2014**
- [x] Technology Application
- [x] Flag: In-collection for technology: ie: **Drones incollection**
- [x] User role
- [x] Organization name
- [x] Organization type
- [x] Attachments name or description
- [x] Attachment handler: ie: **technologies with attachments**

**Comment by arthursoares** [comment]
Depois dá uma olhada @rafaelcorreiapoli

**Comment by rafaelcorreiapoli** [comment]
Ok! vou estudar, montar alguns esquemas e postar aqui para validação :)

**Comment by rafaelcorreiapoli** [comment]
Você imagina um campo de busca que retorne todo o tipo de resultado (como por exemplo a busca do facebook, que retorna usuários, grupos, eventos, etc) ou um filtro para especificar qual entidade você procura?

**Comment by rafaelcorreiapoli** [comment]
@arthursoares O que são as Labels?

**Comment by rafaelcorreiapoli** [comment]
![attachments](https://cloud.githubusercontent.com/assets/12840136/12281424/3529e9a8-b97d-11e5-88f8-d400d71edae8.png)
![organization search](https://cloud.githubusercontent.com/assets/12840136/12281427/352cc9ac-b97d-11e5-8cb8-a17d8f1ffb1d.png)
![projects search](https://cloud.githubusercontent.com/assets/12840136/12281425/352c2c72-b97d-11e5-9017-bd853c3e2512.png)
![tech search](https://cloud.githubusercontent.com/assets/12840136/12281428/352d6c4a-b97d-11e5-9962-4fb3651f8a22.png)
![user search](https://cloud.githubusercontent.com/assets/12840136/12281429/353412a2-b97d-11e5-8d0e-d5a638701fb1.png)
![index](https://cloud.githubusercontent.com/assets/12840136/12281426/352cadc8-b97d-11e5-939f-e9ae7ad0e218.png)

**Comment by arthursoares** [comment]
@rafaelcorreiapoli Erro meu, Labels ==> Tags. Corrigi lá

**Comment by arthursoares** [comment]
> Você imagina um campo de busca que retorne todo o tipo de resultado (como por exemplo a busca do facebook, que retorna usuários, grupos, eventos, etc) ou um filtro para especificar qual entidade você procura?

Acho que a busca principal seria dessa forma. Nas regras que coloquei lá em cima. Imagino que seriam as principais buscas. 

> Algumas entidades tem campos especificos que não poderiam ser usados em uma busca genérica (como por exemplo Type da organization)

Pode dar um exemplo melhor? Eu acho que o type seria com um handler. É possível? tipo como fazemos no google? `site:envisioning.io` ou `filetype:pdf`. O que poderíamos fazer para simplificar é apenas colocar um tooltip expandido explicando os handlers.

> Acredito que fazer um filtro booleano pra especificar qual entidade você procura (e aí já renderizar o formulário de busca adequado) seja a melhor alternativa.

> Imagina um dropdown com nossas entidades (Tech, Org, People...)
> Ao selecionar Tech, o formulario de busca já assume a forma que precisa para realizar uma busca por Tech: Um campo de texto (que buscará em Title e Description, dando mais relevância à Title, assim como o google faz) e um input tag que fará match de tags, por relevância também (uma tech que tenha somente a tag que você inputou terá mais relevância que uma tag que tenha esta e mais outra) Ambos com fuzzy search, podendo regular o nivel de fuzziness

Acho que a tela expandida para Tecnologias funciona muito bem, pois tem o maior range de filtros e detalhes.

> Outro ponto é que se a busca envolver diversos parametros (por exemplo title+description E tags, no caso da busca por Tech), os filtros são combinados e é feito um cálculo de relevância, podemos inclusive atribuir pesos e tudo mais

:+1:

**Comment by rafaelcorreiapoli** [comment]
Sobre os handlers é sim possível, porém não acredito que para o nosso piloto seja necessário. Vai dar um trabalho grande e talvez este sistema de busca que bolei aí nos wireframes (e que é mais simples de se fazer) já atenda as necessidades. O que você acha de seguirmos num primeiro momento esta linha que propus?
O que quis dizer é: imaginando que temos apenas um campo de busca (um input de texto) que busca em todas as entidades (Orgs, Techs, Users...), algumas propriedades particulares de cada entidade (como por exemplo Type da Org) não poderia entrar como parâmetro de busca. O jeito seria mesmo fazer com handlers, aí com uma string você representa diversas informações (operadores lógicos e tudo mais) porém ficaria realmente mais complicado de fazer para este primeiro momento.

Podemos fazer uma caixa de texto de "busca global" que busca apenas pelo Title/Name de cada entidade

O que acha?

**Comment by arthursoares** [comment]
```
Sobre os handlers é sim possível, porém não acredito que para o nosso piloto seja necessário. Vai dar um trabalho grande e talvez este sistema de busca que bolei aí nos wireframes (e que é mais simples de se fazer) já atenda as necessidades. O que você acha de seguirmos num primeiro momento esta linha que propus?
``` 

Ok. Vamos com isso.

**Comment by arthursoares** [comment]
**Update 19/jan**

- [ ] Search field must search within Title and Description of all entities.
- [ ] Search field must search within Tags of all entities.

**Comment by rafaelcorreiapoli** [comment]
O campo "Description" sempre tem um campo "Status" o acompanhando
Isso deve ser parâmetro de busca?
Ou eu procuro pelo texto digitado em todas as Descriptions da entidade, independente do status?

**Comment by rafaelcorreiapoli** [comment]
Uma outra questão: sobre sinônimos
No elastic search há uma funcionalidade muito legal de synonyms, que é para casos do tipo:
vou dizer que essas 3 ocorrências são sinonimos:
[usa, united states, united states of america]
entao em qualquer lugar que houver a ocorrencia de "usa", tudo se passa como se "usa"  pudesse ser "united states" ou "united states of america"

então, se há um documento que diz
"usa is wealthy"

e eu procurar por "usa", por "united states" ou "united states of america", este documento vai voltar como resultado. é realmente como se existissem dentro desta sentença, 3 sentenças diferentes:
"usa is wealthy", "united states is wealthy" e "united states of america is wealthy"

Será que este modelo faz sentido para synonyms de Tecnologia (ou de qualquer outra entidade)?
supondo que há uma tecnologia "Drone"
e nós coloquemos como sinônimo "Coisa voadora", "Veiculo aéreo não tripulado"

Quando a pessoa procurar por "drone", tudo se passa como se ela tivesse procurado por "coisa voadora" ou por "veiculo aéreo não tripulado", sendo assim, se na Description de um Project ocorrer o texto "veiculo aéreo não tripulado", este documento irá vir como resultado, faz sentido não é?

Mais que isso, se houver as palavras "veiculo" e "tripulado" em algum outro campo de algum entidade, ela também voltará como resultado (porém com uma relevância bem menor). Faz sentido também, não?

**Comment by arthursoares** [comment]
> O campo "Description" sempre tem um campo "Status" o acompanhando
Isso deve ser parâmetro de busca?

Não! Vamos pesquisar somente a descrição aprovada.

--

**Sinônimos**

São uma questão bem importante para nós. Como fazemos na prática essa correlação entre eles? Os cenários que você exemplificou funcionam perfeitamente. O `Name` sempre vai ter mais relevância do que `Description`

**Comment by rafaelcorreiapoli** [comment]
Então na verdade o Status é sim um parâmetro de busca: devo buscar apenas em descriptions que estejam "Published", correto?

Sobre sinônimos, na verdade o proprio sistema irá se comunicar com o elasticsearch e determinar os synonyms de acordo com o que o usuário preencher quando cadastrar a tecnologia.
Por exemplo, ao cadastrar a tecnologia "drone", o usuário coloca como sinônimo os valores "Veiculo aéreo não tripulado" e "Coisa voadora". Ao enviar o formulário, o nosso sistema irá avisar o elasticsearch de que "drone", "veiculo aereo nao tripulado" e "coisa voadora" são sinonimos, ou seja: sempre que encontrar qualquer um dos três **em qualquer lugar do banco de dados**, assuma que os três são equivalentes

**Comment by michellzappa** [comment]
Elasticsearch = FODA. Isso vai ser muito útil.

**Comment by rafaelcorreiapoli** [comment]
Até me pergunto se não faz mais sentido você cadastrar sinônimos num lugar separado e não na hora de cadastrar a tecnologia, pois estes sinônimos vão influenciar o banco de dados de busca como um todo
Eu não sei se to conseguindo ser claro haha

**Comment by rafaelcorreiapoli** [comment]
@arthursoares, poderia me passar um json com diversas entradas reais do banco de dados? tech, orgs, etc.. preciso delas para regular os infinitos parâmetros de busca do elastic search hehe

**Comment by arthursoares** [comment]
Farei isso, te mando amanhã!
On Sat, Jan 23, 2016 at 04:23 Rafael Ribeiro <notifications@github.com>
wrote:

> @arthursoares <https://github.com/arthursoares>, poderia me passar um
> json com diversas entradas reais do banco de dados? tech, orgs, etc..
> preciso delas para regular os infinitos parâmetros de busca do elastic
> search hehe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/techdb/issues/32#issuecomment-174153576>.
>
-- 
+55 11 96960.6666
http://arthur.wtf

**Comment by NDuma** [comment]
Synonyms should be weighted.

**Comment by NDuma** [comment]
[ExamineIs#2Vote=18]
(https://www.powerthesaurus.org/interrogate/synonyms)
& [ExaminationIs#1Vote=16 + ExamineIs#19Vote=3](https://www.powerthesaurus.org/interrogation/synonyms)

Weight by total #votes & #of entries for baseline score.

User Connections to Specific Technology & Popularity.
Weightings are directional and tied to nodes.

Actually Searching Now:

[1/~25+ pages open now - This's Site Personalized & has a simple walkthrough](blog.comperiosearch.com/blog/2014/02/05/dynamic-search-ranking-using-elasticsearch-neo4j-and-piwik/) 
btw @michellzappa I checked for aternatives to GoogleAnalytics [Piwik](http://piwik.org/) is one I'd seen before; however, it didn't have as many 'bells & whistles' as GA in the (slightly older) comparisons I read. https://github.com/envisioning/readiness.io/issues/91

[Heat Map Style Implementation @Thesaurus.com](http://www.thesaurus.com/browse/interrogate)

**Comment by michellzappa** [comment]
Thanks, Nick.
We’ll let you know when you can help out with code.
