### ISSUE TITLE
dashboardStat

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#33]
Card to hold information about the entity on the main dashboard.

### Specification
- Unique color
- Unique icon
- Can be used as a link to the entity's main page
- Will show useful information about the entity (number of doc's, etc...)

4 different cards:
- Users
- Organizations
- Projects
- Technologies

**Version 2 (current)**
**- Fix plural naming**
![component card status](https://cloud.githubusercontent.com/assets/4376835/12218574/8265e2dc-b70a-11e5-85e6-0e7733d9e964.png)

**Version 1**
![component card status](https://cloud.githubusercontent.com/assets/4376835/12217952/5bd4c38a-b6f7-11e5-88d0-a252d19b23e3.png)

**Comment by arthursoares** [comment]
@rafaelcorreiapoli temos uma Label para os components/elements. 

<img width="539" alt="screen shot 2016-01-09 at 11 09 10 pm" src="https://cloud.githubusercontent.com/assets/533339/12219323/05a99c2c-b726-11e5-9355-23594fd7e4e9.png">

Vamos utilizar? É mais fácil de fazer tracking do que colocar no title "component"
