### ISSUE TITLE
recentUpdates

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#34]
List that will show the most recent updates on the database

### Specification

Each row will contain:
- Unique icon of the entity
- Color representing the operation (insert, update, delete)
- The username
- A short description of the user's action
- Date of the operation

Tracked operations:
- Insert
- Remove 
- Updates
- **more[?]**

**Version 2**
![component recent updates](https://cloud.githubusercontent.com/assets/4376835/12218135/437d8460-b6fd-11e5-819e-88cd4fe88f3c.png)

**Version 1**
![component recent updates](https://cloud.githubusercontent.com/assets/4376835/12218076/9e1e29e4-b6fb-11e5-9909-6e1b0ca966c5.png)

**Comment by arthursoares** [comment]
:+1:
