### ISSUE TITLE
orgAboutBox

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#35]
A card to display detailed info about the Organization.

### Specification
- Name
- Image with logo
- Year
- Country with flag
- Type
- Url's with icons
- Button do Edit (Pencil Icon)

**Version 2 (current)**
Use #20 as a reference.

**Version 1**
![organization card](https://cloud.githubusercontent.com/assets/4376835/12218295/060b72cc-b702-11e5-9c25-f3a46ee6c433.png)

**Comment by arthursoares** [comment]
Cool! Please use #20 as a reference!

**Comment by rafaelcorreiapoli** [comment]
I was thinking that it should look more like a technologyCard #11 
Would #20 's "about" section fit better? (with an image for the logo)

**Comment by arthursoares** [comment]
I vote for #20 with image/logo. :)
On Sun, Jan 10, 2016 at 00:09 Rafael Ribeiro <notifications@github.com>
wrote:

> I was thinking that it should look more like a technologyCard #11
> <https://github.com/envisioning/techdb/issues/11>
> Would #20 <https://github.com/envisioning/techdb/issues/20> 's "about"
> section fit better? (with an image for the logo)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/techdb/issues/35#issuecomment-170300659>.
>
-- 
+55 11 96960.6666
http://arthur.wtf

**Comment by michellzappa** [comment]
+1 #20
