### ISSUE TITLE
Screen: orgEntry

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#37]
A screen to show everything about a specific organization

## Specification
Composed by two main components:
### Organization card on the left panel
orgCard #35

### Tabholder on the right panel with these tabs:
- Projects
- Techs
- Attachments

Each tab will have a simpleList #36 with the associated entities and a link for them

![screen organization entry](https://cloud.githubusercontent.com/assets/4376835/12218523/e6b105ca-b708-11e5-8062-c338f2390be5.png)

**Comment by arthursoares** [comment]
Already exists at #27
