### ISSUE TITLE
briefCard

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#39]
A card to show generic information about any entity, will be used for example on Grid Views when displaying results from an ElasticSearch' search
## Specification
Will contain:
- Image
- Title
- Subtitle
- Optional array of generic information
- A place to hold any other templates to be embedded on the card, usually a template with **actions** (Edit, Delete, Etc)

![aboutcard](https://cloud.githubusercontent.com/assets/12840136/12218454/a6752330-b706-11e5-9c60-7f38420214e3.png)

**Comment by arthursoares** [comment]
Let's use the INSPINIA ibox top-right toolbar / dropdown for buttons and actions (Ie: Edit / Delete)

Check this:
http://envisioning.github.io/techdb/insinia_html/tabs_panels.html

<img width="1422" alt="screen shot 2016-01-09 at 11 22 58 pm" src="https://cloud.githubusercontent.com/assets/533339/12219387/f607d94e-b727-11e5-95e3-aa5e4ea1aa1c.png">

**Comment by arthursoares** [comment]
I'd place the fundamental ones as icons.

This will eventually get more complex as we advance. I.e.: contextual drop
down menus for each application or parent screen.
On Sun, Jan 10, 2016 at 00:04 Rafael Ribeiro <notifications@github.com>
wrote:

> Ok! should we place the Edit/Delete inside a dropdown, on an "actions"
> icon or place the Edit/Delete buttons directly as icons ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/techdb/issues/39#issuecomment-170300515>.
>
-- 
+55 11 96960.6666
http://arthur.wtf

**Comment by michellzappa** [comment]
Agree. Let's keep hidden elements to a minimum!
