### ISSUE TITLE
Screen: mainDashboard

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/techdb#41]
## Specification
The main dashboard is the first screen after user login. Shows relevant information about techDB entities and recent updates.

#### Component Dependencies
- dashboardStat #33 
- recentUpdates #34 
- **more[?]**

#### Complete Screen
![screen main dashboard](https://cloud.githubusercontent.com/assets/4376835/12218678/10600010-b70e-11e5-8eba-47823d24e201.png)

**Comment by arthursoares** [comment]
@rafaelcorreiapoli lets not create duplicate entries, please. This will make it confusing to followup and centralize information.

This already exists at #15 with features.

**Comment by arthursoares** [comment]
Merged with #15.
