### ISSUE TITLE
Screen: login

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#42]
Login functionalities for TechDB
## Specification
Login screen with some login options:
- Password
- Google +
- Facebook

User accounts features:
- The user should be invited by the Administrator through the admin panel. An email will be sent to the user with a link to activate and set his password
- The user can recover his password by email

![login](https://cloud.githubusercontent.com/assets/12840136/12218698/a61f7a2c-b70e-11e5-8cbe-ee2cbf98ce92.png)

**Comment by arthursoares** [comment]
Already exists at #14.
