### ISSUE TITLE
Screen: userDashboard

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#43]
A screen to view and manage all users
### Manage
A search box that will regex search all row's texts
Button group to toggle between *List view* and *Grid View*
A FAB (Floating action button) to add new entry

#### List View:
Datatable with these columns:
- Name
- Group (roles)
- Last Time Access
- Status (online or offline)
- Actions \*

\* Edit: opens a modal to quickly edit organization
\* Delete: opens a confirmation dialog to delete organization
\* Manage Group Permissions: Opens a modal to change user's role
\* Manage Project Permissions: Opens a modal to view/grant/revoke projects permissions for this particular user #44

The table can be sorted by any column, will have pagination and a dropdown to select how many rows will be shown per page
![list view](https://cloud.githubusercontent.com/assets/12840136/12218947/e9649b66-b716-11e5-95aa-4e4c63fe8f3f.png)

### Grid View
A grid of aboutCards #39  
![grid view](https://cloud.githubusercontent.com/assets/12840136/12218949/f0fa6d92-b716-11e5-9f30-bc1597c8493b.png)

**Features [?]**:
Pagination ?
Infinite Scroll ?
Sorting ?

### Complete screen
![complete screen](https://cloud.githubusercontent.com/assets/12840136/12218965/95baa3c4-b717-11e5-92f2-f0f25e8891cb.png)

**Comment by arthursoares** [comment]
Merged with #24
