### ISSUE TITLE
userProjectPermissions

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/techdb#44]
### Specifications

This permissions grants the user access to edit the project content. **Only Admins can Create and Delete projects.**

#### Complete Screen **[Modal]**
![modal user project permissions](https://cloud.githubusercontent.com/assets/4376835/12218991/1e1bac86-b718-11e5-8d7b-5c02e4a36d9d.png)

**User Typing (typeahead)**
![modal user project permissions typing](https://cloud.githubusercontent.com/assets/4376835/12218990/1e01d0d6-b718-11e5-9d58-15ab46a80a0a.png)

**Item Added**
![modal user project permissions added](https://cloud.githubusercontent.com/assets/4376835/12218989/1db67fdc-b718-11e5-8e88-30018420f8cd.png)

**If user is Admin**
![modal user project permissions admin case](https://cloud.githubusercontent.com/assets/4376835/12219127/ab9b418a-b71c-11e5-8e73-b107b7062939.png)

**Comment by arthursoares** [comment]
- [ ] Request: We should be able to see permissions from #20 projectEntry context. Which users have access to this project.

**Comment by rafaelcorreiapoli** [comment]
We can create a equivalent component "projectUsersPermissions", that works for projects context.
The title of the modal will be the project name and the list will search on Users database

**Comment by arthursoares** [comment]
Seems to work :)
On Sat, Jan 9, 2016 at 23:57 Rafael Ribeiro <notifications@github.com>
wrote:

> We can create a equivalent component "projectUsersPermissions", that works
> for projects context.
> The title of the modal will be the project name and the list will search
> on Users database
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/techdb/issues/44#issuecomment-170300315>.
>
-- 
+55 11 96960.6666
http://arthur.wtf
