### ISSUE TITLE
userAboutBox

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#45]
A card to display detailed info about the User.

### Specification
- Name
- User picture, when clicked a modal is open
- Role
- Affiliation
- Country
- Contacts on social networks
- Bio

![user card](https://cloud.githubusercontent.com/assets/12840136/12219388/0656e60a-b728-11e5-8844-802b80cc7fd0.png)

**Comment by arthursoares** [comment]
:+1:
