### ISSUE TITLE
manageUserRoles

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/techdb#46]
### Specification
Manage user groups to give them permissions on techDB.

- You can find users to change their groups by searching with the search box.
- If you come from a user table (manage user group action), the selected user will be displayed by default
- A confirmation modal after click in the label to confirm the operation

### Complete Screen [Modal]
![manage user groups](https://cloud.githubusercontent.com/assets/4376835/12219213/65876a58-b720-11e5-940a-2f68acf05334.png)

**Comment by arthursoares** [comment]
Just referencing to #25 for permissions and rules.

**Comment by lnmunhoz** [comment]
Missing confirmation modal for changes.
