### ISSUE TITLE
Screen: userEntry

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#47]
A screen to show everything about a specific User

## Specification
Composed by three main components:
### User card on the left panel
userCard #45 

### Recent Activities for this user
recentUpdates #34 

### Projects that this user is working
simpleList #36 
![complete screen v2](https://cloud.githubusercontent.com/assets/12840136/12219269/5570ef56-b723-11e5-8b72-6e055bcb40c2.png)

**Comment by arthursoares** [comment]
Merged with #25
