### ISSUE TITLE
searchContainer

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/techdb#48]
## Specification

- Search Box with Elastic Search
- A switch for Table View and Grid View
- Infinite Loading

![orgdashboarddatatable](https://cloud.githubusercontent.com/assets/12840136/12218578/8c91b1f0-b70a-11e5-9dc5-5ef4a307d642.png)

### Grid View
A collection of aboutCards #39  
![orgdashboardgridview](https://cloud.githubusercontent.com/assets/12840136/12218575/830e4a9e-b70a-11e5-92cf-56c8b3f2597d.png)

**Comment by lnmunhoz** [comment]
We decided to remove pagination of Table View and use inifite scrolling to be more effective. What you @arthursoares ?

![table view](https://cloud.githubusercontent.com/assets/4376835/12302742/eb06b3b0-ba0d-11e5-97f2-a9c5be1d541c.png)

**Comment by arthursoares** [comment]
:+1:
