### ISSUE TITLE
attachmentAboutBox

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/techdb#49]
### Specification

A card to display information about one attachment.

- Title that redirects to the file
- User that created the attachment
- Upload date
- Related Projects
- Related Organizations
- Related Technologies
- Knows how to render by the filetype

![attachmentcard](https://cloud.githubusercontent.com/assets/4376835/12305817/c299033c-ba1d-11e5-8a27-76e9358389b4.png)

**Comment by arthursoares** [comment]
Don't forget that attachments will also be URLs: Articles, Blog posts, websites, etc…

**Comment by lnmunhoz** [comment]
:+1:

**Comment by michellzappa** [comment]
Attachment should also have a Type (or Tag), so we can display them
intelligently. For example: show all links tagged 'YouTube ' as a list. Or
all 'Article', etc.

**Comment by rafaelcorreiapoli** [comment]
So we must add a 'tags' array field to Attachments collection in #7 db scheme

**Comment by michellzappa** [comment]
Yes please.
