### ISSUE TITLE
attachmentThumbnail

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/techdb#51]
### Specification

- Default image for pdfs, xdocs, etc...
- Image with the filetype is .png, jpg, etc...
- Icon by the filetype

![attachmentthumbnail](https://cloud.githubusercontent.com/assets/4376835/12306641/e9b56600-ba21-11e5-8aa4-d3b8d52bbf96.png)

**Comment by arthursoares** [comment]
**FIY**: Attachments most likely will be URLs.

**Comment by lnmunhoz** [comment]
For Urls we can get the metadata from the page and show on the thumbnail. What you think?

**Comment by arthursoares** [comment]
:+1: That is it.

On Fri, Jan 15, 2016 at 8:12 PM, Lucas N. Munhoz <notifications@github.com>
wrote:

> For Urls we can get the metadata from the page and show on the thumbnail.
> What you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/techdb/issues/51#issuecomment-172109692>.
>



-- 
http://arthur.wtf
+55 11 96960.6666

**Comment by michellzappa** [comment]
+1 for pulling thumbnails and metadata. Very useful.
