### ISSUE TITLE
formInsertTech

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#52]
A simple form to insert technologies with client and server-side validations

- Name -> input text
- Synonyms -> tags input
- Status -> select input
- Tags -> tags input
- Organization -> select input

The other fields must have a more complex UI that we need to discuss

**Comment by arthursoares** [comment]
- We definitely need description, make it without versioning now.

**Comment by rafaelcorreiapoli** [comment]
Ok, the problem is more about how will the user input information about Descriptions, since it's an array. I think that makes more sense for the user to input descriptions on a later time, maybe on #17 instead of inputting them on creation time of the Tech
