### ISSUE TITLE
Discussion on Cards

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#54]
Hi! On a comment in Google Sheets, @arthursoares said that we should have a different card for each entity (tech, org, etc) when showing them on a Grid View, for example after an ElasticSearch search.
I think that showing the cards that are present on #35 #45 #49 at the same time will make the grid and the visualization of results a mess. Each one has different sizes and different properties that should not be shown all at once in a single context
What I suggest is that we still use the concept of a "generic card" (that we called about card #39), but with this design:
http://webapplayers.com/inspinia_admin-v2.4/ecommerce_products_grid.html

To differ them, we could place an icon/color unique to the entity on the place where the example says "$10". This generic card will be used to display a brief of the document behind it.
It could also be called "briefCard"

**Comment by michellzappa** [comment]
Perfect IMO.

**Comment by arthursoares** [comment]
Ok! :+1:

**Comment by rafaelcorreiapoli** [comment]
I had a conversation today with @arthursoares and we concluded that the **<>cards**'s will be done on the second milestone. They are very different than what **I** was calling "cards". Actually, everything I was calling cards are now**aboutBoxes**. They are not very smart as cards since they don't mutate to fit context and they show a lot of information, in contrast of cards
