### ISSUE TITLE
Upload to S3 with data redundance on Cloudinary for transformations

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#55]
Issues that need to be revisited after this implementation:
#46 
#35 
#45

**Comment by rafaelcorreiapoli** [comment]
I had some issues replicating the data from S3 to Cloudinary (it's kind tricky, thats why they have a built-in integration on their paid plan)
So I decided to make things a little bit different:
- When the uploaded image arrives on our NodeJS server, I use graphicsmagick to transform the image to various sizes that we will use on our app. So when I upload something, it's store on three folders on our S3:
/originals:  the original imagem
/thumbs:  a thumb version of the image (resized to 100x100, in case it's larger than this)
/about-boxes: a version of the image that will be used on aboutBoxes (resized to 500x500 in case it's larger than this)
/cards: a version of the image that will be used on cards (640x360, AR 16:9)

To guarantee the aspect ratio of the image, all screens that will have an upload functionality will use #57, so the user will have to crop it on the desired AR

**Discussion**:
When setting the logo for an organization, we will want the user to crop a 1:1 image, so it will be used on #35 and in some thumb of that organization
But for cards, we will need a 16:9 version.
**Option 1**: Make the user crop two different images: one to be used on cards (16:9) and one to be used on aboutBoxes and thumbnails (1:1)
**Option 2**: Automatically crop the horizontal center of an 1:1 image to make it 16:9

**Comment by arthursoares** [comment]
This is sounding a tad more complicated than it should be.

- Users will upload images in whatever aspect ratio as the original file is.
- Logos for Organizations will not be cropped in 1:1 (square). They should
be **contained** inside a square box or whichever view is exhibited.
- The same goes for technology images. They maintain their original aspect
ratio and are **manipulated** according to wherever they're displayed


This is why we used cloudimage. https://cloudimage.io The examples on the
landing page explains exactly what we need/want to achive. If cloudinary is
not capable of performing this, we stick with cloudimage?

And a correction, images on the technology card are **3:2** and not
**16:9**.





On Thu, Feb 4, 2016 at 4:26 PM Rafael Ribeiro <notifications@github.com>
wrote:

> I had some issues replicating the data from S3 to Cloudinary (it's kind
> tricky, thats why they have a built-in integration on their paid plan)
> So I decided to make things a little bit different:
>
>    - When the uploaded image arrives on our NodeJS server, I use
>    graphicsmagick to transform the image to various sizes that we will use on
>    our app. So when I upload something, it's store on three folders on our S3:
>    /originals: the original imagem /thumbs: a thumb version of the image
>    (resized to 100x100, in case it's larger than this) /about-boxes: a version
>    of the image that will be used on aboutBoxes (resized to 500x500 in case
>    it's larger than this) /cards: a version of the image that will be used on
>    cards (640x360, AR 16:9)
>
> To guarantee the aspect ratio of the image, all screens that will have an
> upload functionality will use #57
> <https://github.com/envisioning/techdb/issues/57>, so the user will have
> to crop it on the desired AR
>
> *Discussion*:
> When setting the logo for an organization, we will want the user to crop a
> 1:1 image, so it will be used on #35
> <https://github.com/envisioning/techdb/issues/35> and in some thumb of
> that organization
> But for cards, we will need a 16:9 version.
> *Option 1*: Make the user crop two different images: one to be used on
> cards (16:9) and one to be used on aboutBoxes and thumbnails (1:1)
> *Option 2*: Automatically crop the horizontal center of an 1:1 image to
> make it 16:9
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/techdb/issues/55#issuecomment-179981568>.
>
-- 
+55 11 96960.6666
http://arthur.wtf

**Comment by rafaelcorreiapoli** [comment]
So the image will maintain it's aspect ratio and should be contained on the desired size that we specify, right? If their ARs are different, should I pad the image? I'm concerned about that because if we don't guarantee that all card images are 3:2, we will be displaying cards on different sizes or we will lose parts on the image to make it fit the 3:2 AR on the card

**Comment by michellzappa** [comment]
Why aren't we using Cloudimage? To much room for mistake?

**Comment by arthursoares** [comment]
Sorry,

Logos: will be contained - priority is to display them entirely
Tech images: will be cropped - priority is to fit in the aspect ratio.

On Thu, Feb 4, 2016 at 4:51 PM Rafael Ribeiro <notifications@github.com>
wrote:

> So the image will maintain it's aspect ratio and should be contained on
> the desired size that we specify, right? If their ARs are different, should
> I pad the image? I'm concerned about that because if we don't guarantee
> that all card images are 3:2, we will be displaying cards on different
> sizes or we will lose parts on the image to make it fit the 3:2 AR on the
> card
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/techdb/issues/55#issuecomment-179998449>.
>
-- 
+55 11 96960.6666
http://arthur.wtf

**Comment by rafaelcorreiapoli** [comment]
@michellzappa I wanted to store all files uploaded to TechDB on a single place (S3) and found too much trouble trying to make our S3 upload the images to Cloudinary when they arrive there. So I implemented the transformation libraries on our server and the images are transformed before they are sent to s3 (using graphicsmagick)
http://aheckmann.github.io/gm/docs.html
it has all functionalities we need: crop, resize, etc
@arthursoares 
Ok! should I crop on center?

**Comment by rafaelcorreiapoli** [comment]
Another solution is to upload images to cloudinary/cloudimage and other kind of files to our S3... then we can think on a way to sync them on the other milestones, if we need to

**Comment by arthursoares** [comment]
Can't we just use cloudinary for displays and our own bucket for
backup/storage of the original file?

On Thu, Feb 4, 2016 at 5:00 PM Rafael Ribeiro <notifications@github.com>
wrote:

> Another solution is to upload images to cloudinary/cloudimage and other
> kind of files to our S3... then we can think on a way to sync them on the
> other milestones, if we need to
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/techdb/issues/55#issuecomment-180002785>.
>
-- 
+55 11 96960.6666
http://arthur.wtf

**Comment by michellzappa** [comment]
Keep it simple! :)

**Comment by rafaelcorreiapoli** [comment]
Yes, I think it's the best way. I will setup S3 policies to allow cloudimage/cloudinary to download the images from there
Sorry for the complication guys :P
