### ISSUE TITLE
Select file to upload

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#57]
This component lives inside a modal, it will show the user three source options:
- the filesystem (with <input type="file">, filtering by the desired file type) 
- the webcam (if we need an image)
- some url on the web

If we are looking for an image, after the user picks one from one of the above sources, it will be drawn on a canvas where the user can crop it. We can define the aspect ratio of the output image as a parameter of the component
If it's not an image, the user will be presented with an Icon representing the file type (doc, pdf, etc)
When the upload begins, it will display a status bar with the upload progress
When the upload is finished, a success message will be shown and the modal will be closed

This component will be used on every screen that needs some kind of file upload (attachments, user profile, org description for logo, etc...)

**Comment by michellzappa** [comment]
Perfect!
