### ISSUE TITLE
Point tdb.envisioning.io to TDB installation

### ISSUE THREAD

**Issue by michellzappa** [envisioning/techdb#59]
Switch DNS, etc.

**Comment by arthursoares** [comment]
:) It is on.

**Comment by michellzappa** [comment]
My bad! Thanks for staying on top of things :)

**Comment by michellzappa** [comment]
That being said: I seem to be receiving a HTTPS warning because of how the domain is forwarded. Is that fixable?

**Comment by lnmunhoz** [comment]
We can setup the dns if you guys want

**Comment by arthursoares** [comment]
Yep. It will be, I think we just need to buy an SSL certificate.

On Wed, Feb 10, 2016 at 2:55 PM Michell Zappa <notifications@github.com>
wrote:

> That being said: I seem to be receiving a HTTPS warning because of how the
> domain is forwarded. Is that fixable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/techdb/issues/59#issuecomment-182477358>.
>
-- 
+55 11 96960.6666
http://arthur.wtf
