### ISSUE TITLE
userCard

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#62]
We will use this card on userDashboard to display the users on TechDB, within the search component

http://webapplayers.com/inspinia_admin-v2.4/contacts.html
http://webapplayers.com/inspinia_admin-v2.4/contacts_2.html

Which one do you prefer?
I vote for the first one

**Comment by michellzappa** [comment]
I’m OK with #1 as well, especially because it keeps Users visually distinct
from Technologies.

**Comment by arthursoares** [comment]
First one.
