### ISSUE TITLE
attachmentsAdd

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/techdb#63]
We forgot to prototype the attachmentsAdd component. Following the specs from attachmentEntry #29, we design this screen in three different sections.

### **Website Reference**

The user will input the url (blog post, article, youtube video, etc) and TechDB will crawl the metadata from the website. We are currently crawling website `title`, `description` and `image`.
After TechDB crawl the data, the fields are auto completed, but the user can change them manually as wanted.

Preview
![website reference](https://cloud.githubusercontent.com/assets/4376835/12996525/df42ae5a-d117-11e5-8eea-859b17a4259e.png)

### File from url
The user will input a url that contains a file. TechDB will download the file, store on its own cloud and autocomplete the `name` field with the name of the file. It can be changed manually too.

Preview
![file from url](https://cloud.githubusercontent.com/assets/4376835/12996745/b42e4eca-d119-11e5-8ebd-39874dc528d7.png)

### File upload
A basic upload system from local hard drive to TechDB cloud. The behaviour are the same as **File from url** but works locally.

Preview
![file upload](https://cloud.githubusercontent.com/assets/4376835/12996757/c31ec6ee-d119-11e5-8194-a654848b7b25.png)

Need feedback from @arthursoares and @michellzappa about this spec. 

Balsamiq File [here](https://github.com/envisioning/techdb/files/127393/attachmentAdd.bmpr.zip)

**Comment by michellzappa** [comment]
Works for me.

**Comment by lnmunhoz** [comment]
Nice! Waiting for @arthursoares feedback now.

**Comment by arthursoares** [comment]
Seems ready for me.

**Comment by lnmunhoz** [comment]
:+1:

**Comment by lnmunhoz** [comment]
@arthursoares What kind of files you guys most work? We need to set some filters on upload for security purposes. Can you give some examples like .pdf, .csv, .xls and other extensions?

**Comment by michellzappa** [comment]
PDF and images (png, jpeg, gif) mostly.

**Comment by arthursoares** [comment]
Might have an .AI, .EPS & .ZIP
