### ISSUE TITLE
Insert a section title on the Sidebar Popover

### ISSUE THREAD

**Issue by arthursoares** [envisioning/techdb#67]
<img width="229" alt="screen shot 2016-02-15 at 8 57 00 pm" src="https://cloud.githubusercontent.com/assets/533339/13062618/30f416be-d427-11e5-976b-67a8ab58962c.png">

above "Dashboard" it would be good to have the section title and a <hr />

**Comment by lnmunhoz** [comment]
Check! :+1: 
![screenshot from 2016-02-28 22 23 38](https://cloud.githubusercontent.com/assets/4376835/13383554/0bfbe4d4-de6a-11e5-8bcb-f1e80bdc0149.png)
