### ISSUE TITLE
Configure automated deployment

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/techdb#68]
- [x] Code Climate (Waiting for contact support to solve unknown error)
- [x] Travis-CI build
- [x] Travis-CI deployment to modulus
- [x] Encrypt modulus token on .travis.yml

**Comment by arthursoares** [comment]
Isn't it turned-on on MOdulus?

**Comment by lnmunhoz** [comment]
@arthursoares Modulus is just a deployment cloud solution. I'm creating a integration with github that automatically push it to modulus and make some code tests to ensure quality.
