### ISSUE TITLE
shortIt function on strings with html tags

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#75]
On the search screen, matching text in "names" are highlighted (briefCard). Since shortIt cuts a substring of the name with a fixed len, names with html tags ```(<em></em)``` will have different behaviour.

**Comment by michellzappa** [comment]
Good to know — but we should have zero HTML tags in actual data.

**Comment by rafaelcorreiapoli** [comment]
html tags are inserted in execution time, when the search is done
```javascript
SearchSource.prototype.getTransformedData = function() {
  return this.getData({
    transform(matchText, regExp) {
      matchText = String(matchText);

      if (matchText.replace) {
        return matchText.replace(regExp, '<em>$&</em>');
      }
      return matchText;
    },
    sort: {
      _score: -1
    }
  });
};
```

**Comment by rafaelcorreiapoli** [comment]
The problem is that we cut the text on briefCard to fit correctly..
if the name is 
Abcdefghijklmnopq
we transform it to:
Abcdef... (6 characters)

The problem is that if we serach for "a", the actual name being displayed will be
<em>A<.... (6 characters)

**Comment by michellzappa** [comment]
Gotcha!

**Comment by rafaelcorreiapoli** [comment]
https://github.com/huang47/nodejs-html-truncate
@lnmunhoz

**Comment by rafaelcorreiapoli** [comment]
fixed with CSS :+1: 
```css
.truncate-text {
  padding: 5px;
  width: 100%;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

learning something new everyday hehehe

**Comment by michellzappa** [comment]
Nice one! → text-overflow: ellipsis;
