### ISSUE TITLE
Titlebar Buttons for default actions in Cards

### ISSUE THREAD

**Issue by arthursoares** [envisioning/techdb#77]
We need to add titlebar buttons such as #17 to cards. The actions should be such as Edit, Delete, change permissions..

Cards like these.
![screen shot 2016-02-23 at 11 34 07 am](https://cloud.githubusercontent.com/assets/533339/13254790/c672cafa-da21-11e5-88db-9a1d88f3fa79.png)

**Comment by rafaelcorreiapoli** [comment]
Could you give me another reference? #17 does not have any images or detailed descriptions

**Comment by lnmunhoz** [comment]
Referencing #62

**Comment by arthursoares** [comment]
@rafaelcorreiapoli sorry, I've referenced it wrong #11 is correct. :)

**Comment by lnmunhoz** [comment]
Reference #87
