### ISSUE TITLE
userDashboard/userEntry: How do I delete an user?

### ISSUE THREAD

**Issue by arthursoares** [envisioning/techdb#78]

**Comment by rafaelcorreiapoli** [comment]
We can add a delete button at the end of the userAboutBox #45 in a section called "Manage", above the section "Bio". It is shown only for admins and require a confirmation by typing the user email

**Comment by rafaelcorreiapoli** [comment]
89e908dfba398f834a423a1404b3541a394dff54

**Comment by michellzappa** [comment]
Works!
