### ISSUE TITLE
userEntry modal: Profile thumbnail not showing

### ISSUE THREAD

**Issue by arthursoares** [envisioning/techdb#80]
![screen shot 2016-02-23 at 11 42 14 am](https://cloud.githubusercontent.com/assets/533339/13254994/b4eca8fe-da22-11e5-9e51-a17ebce519a7.png)

It returns a 404.

**Comment by rafaelcorreiapoli** [comment]
I made some changes in cloudinary's structure to support attacments image and forgot to fix some components, sorry! It will be fixed today

**Comment by rafaelcorreiapoli** [comment]
7bec46806e5929795eea581d75b792c37a202092
