### ISSUE TITLE
Force users to fill some information

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [envisioning/techdb#81]
What information should we force the user to fill after he activated his account?
- First Name
- Last Name
- Username

...

**Comment by michellzappa** [comment]
First & Last = yes
Username = can this just be email?

**Comment by rafaelcorreiapoli** [comment]
Yes, no problem.
What about other fields? Country, Birth, ContactInfo, etc?
(fields in #7)

**Comment by michellzappa** [comment]
Actually, make all fields required. We want complete profiles!

**Comment by lnmunhoz** [comment]
Reference for customInputs: https://github.com/meteor-useraccounts/wiki/blob/master/customInputFields/bootstrap/datepicker.md

**Comment by lnmunhoz** [comment]
For now its just required First Name and Last Name. But its ready for more fields!
