### ISSUE TITLE
Create kadira account

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/techdb#82]
Please @arthursoares create an account at https://ui.kadira.io/sign-up. Its an application monitoring tool that we needs to improve performance and check infrastructure issues.

**Comment by arthursoares** [comment]
```Kadira.connect('gBndziYAiFP6sKw6W', '67b7fcb3-d2b6-4cd0-8e26-f3fe684e02f3');```

@lnmunhoz

**Comment by lnmunhoz** [comment]
Setup 5edf63469963996ad9e728cc317d8663e3792d89 here
