### ISSUE TITLE
How should work files access permissions?

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/techdb#83]
We are hosting files in two different AWS S3 folders.

- tdb/files: All files from `url` or `upload`. Any type of files goes here (including images)
- tdb/images: All profile pictures

These two folders contains a `public-read` permission for now.  We need to think about security level for each kind of file. (If needed)

**Comment by michellzappa** [comment]
Well noted. Public access to these files should not be an issue, IMO.

**Comment by arthursoares** [comment]
Agree. Public access.

**Comment by lnmunhoz** [comment]
Ok! All files are public! Thanks!
